### PR TITLE
Fix build with glibc 2.36

### PR DESCRIPTION
**Pull request by benjamb**
glibc 2.36 has added the pidfd_open function, if sys/pidfd.h exists then
we should include it.

Fixes the following error:

    ../common/common-pidfds.c: In function ‘open_pidfds’:
    ../common/common-pidfds.c:70:26: error: implicit declaration of function ‘pidfd_open’; did you mean ‘fdopen’? [-Werror=implicit-function-declaration]
       70 |                 int fd = pidfd_open(pid, 0);
          |                          ^~~~~~~~~~
          |                          fdopen

### CODE REVIEW

**Comment by benjamb** [comment]
Oops, looks like I missed https://github.com/FeralInteractive/gamemode/pull/379.
